
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author havvanuryanik
 */
import javax.swing.JOptionPane;
import java.io.File;
import java.io.FileWriter;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.charset.Charset;
import java.util.Scanner;
import javax.swing.Timer;


public class ex2 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ex2.class.getName());
    private final String dosyayolu= "/Users/havvanuryanik/Desktop/P2OYUN/txtdosyalar/sifre.txt";
    private final String logdosya = "/Users/havvanuryanik/Desktop/P2OYUN/txtdosyalar/log.txt";
    private boolean sifreMevcutMu = false;
    private String dosyadakiSifre = " ";

    private int hataliGirisSayisi = 0;
    private int gecenSaniye = 0;

    /**
     * Creates new form ex2
     */
  
    private void dosyaVeArayuzKontrolu() {
        File dosya = new File(dosyayolu);
        
        if (dosya.exists()) {
            sifreMevcutMu = true;
            jLabel1.setText("Lütfen şifrenizi girin:");
 

            try {
                Scanner dosyaOkuyucu = new Scanner(dosya);
                
                if (dosyaOkuyucu.hasNextLine()) {
                    dosyadakiSifre = dosyaOkuyucu.nextLine();
                }
                
                dosyaOkuyucu.close(); 
                
            } catch (Exception e) {}
        } else {
            sifreMevcutMu = false;
            jLabel1.setText("Bir şifre belirleyin:");
            
        }
    }
  private void gecenSureSayaciniBaslat() {
        Timer zamanlayici = new Timer(1000, e -> {
            gecenSaniye++;
            jLabelSaat.setText("Geçen Süre: " + gecenSaniye + " saniye");
        }); 
        zamanlayici.start();
    }
  
    private void logKaydet(String durumMesaji) {
        try (FileWriter logYazici = new FileWriter(logdosya, true)) { 
            java.util.Date gercekZaman = new java.util.Date();

            logYazici.write("[" + gercekZaman.toString() + "] - " + durumMesaji + "\n");
        } 
        catch (Exception e) {}
}
    
    
    public ex2() {
        initComponents();
        jPasswordField1.setText("");
        jPasswordField1.setColumns(15);
        dosyaVeArayuzKontrolu();
        gecenSureSayaciniBaslat();
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabelSaat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Şifrenizi Girin");

        jPasswordField1.setText("jPasswordField1");

        jButton1.setText("Giriş");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104)
                        .addComponent(jLabelSaat)))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSaat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String girilenSifre = new String(jPasswordField1.getPassword());
        
        // Boş bırakma kontrolü
        if (girilenSifre.equals("")) {
            JOptionPane.showMessageDialog(this, "Şifre alanını boş bırakmayınız:");
            return;
        }
        
        if (!sifreMevcutMu) {
           
            try {
                FileWriter yazici = new FileWriter(dosyayolu);
                yazici.write(girilenSifre);
                yazici.close(); 
                logKaydet("Kullanıcı şifre oluşturdu, sisteme kaydedildi.");
                
                JOptionPane.showMessageDialog(this, "Oyun açılıyor...");
                oyunuBaslat();
            } 
            catch (Exception e) {}
        } 
        else {
            
            if (girilenSifre.equals(dosyadakiSifre)) {
                logKaydet("BAŞARILI GİRİŞ:");
                JOptionPane.showMessageDialog(this, "Şifre Doğru!");
                gecenSureSayaciniBaslat();
                oyunuBaslat();
            } 
            else {

                hataliGirisSayisi++;
                
                if (hataliGirisSayisi >= 3) {
                    logKaydet("Üst üste 3 defa hatalı şifre girildi!");
                   
                    JOptionPane.showMessageDialog(this, "Program sonlandırılıyor.", "Sistem Kilitlendi", JOptionPane.ERROR_MESSAGE);
                    System.exit(0); 
                } else {
                    int kalanHak = 3 - hataliGirisSayisi;
                    logKaydet("Hatalı Giriş Denemesi: Kullanıcı '" + girilenSifre + "' şifresini denedi. Kalan hak: " + kalanHak);
                    JOptionPane.showMessageDialog(this, "Hatalı Şifre! Kalan hakkınız: " + kalanHak, "Hata", JOptionPane.WARNING_MESSAGE);
                    jPasswordField1.setText("");
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    private void oyunuBaslat() {
            this.dispose(); // Giriş/Şifre ekranını kapatır 
            anaOyunEkrani oyunEkrani = new anaOyunEkrani();
            oyunEkrani.setVisible(true);
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ex2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelSaat;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
